apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  name: test-claim
  namespace: default
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: UnifiIPPool
    name: cluster-pool
