resources:
  - bases/ipam.cluster.x-k8s.io_unifiinstances.yaml
  - bases/ipam.cluster.x-k8s.io_unifiippools.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# Labels to declare contract version compatibility
labels:
  - pairs:
      cluster.x-k8s.io/v1beta1: v1beta2
      cluster.x-k8s.io/v1beta2: v1beta2

# patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
# - path: patches/webhook_in_unifiinstances.yaml
# - path: patches/webhook_in_unifiippools.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# - path: patches/cainjection_in_unifiinstances.yaml
# - path: patches/cainjection_in_unifiippools.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
  - kustomizeconfig.yaml
